CREATE DATABASE IF NOT EXISTS siakad_smaga;
USE siakad_smaga;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash CHAR(64) NOT NULL,
  role ENUM('admin', 'guru', 'siswa') NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS siswa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nisn VARCHAR(20) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  kelas VARCHAR(30) NOT NULL,
  jk ENUM('Laki-laki', 'Perempuan') NOT NULL,
  status ENUM('Aktif', 'Cuti', 'Pindah', 'Drop Out') NOT NULL DEFAULT 'Aktif',
  password_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS guru (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nip VARCHAR(30) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  mapel VARCHAR(100) NOT NULL,
  jk ENUM('Laki-laki', 'Perempuan') NOT NULL,
  status ENUM('Aktif', 'Cuti', 'Pensiun') NOT NULL DEFAULT 'Aktif',
  password_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jadwal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hari VARCHAR(20) NOT NULL,
  jam_ke INT NOT NULL DEFAULT 1,
  jam VARCHAR(30) NOT NULL,
  kelas VARCHAR(30) NOT NULL,
  mapel VARCHAR(100) NOT NULL,
  guru_nip VARCHAR(30) NULL,
  ruang VARCHAR(20) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Mendatang',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY jadwal_kelas_slot_unique (kelas, hari, jam_ke)
);

CREATE TABLE IF NOT EXISTS nilai (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nisn VARCHAR(20) NOT NULL,
  mapel VARCHAR(100) NOT NULL,
  nh INT NOT NULL DEFAULT 0,
  pts INT NOT NULL DEFAULT 0,
  na INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY nilai_siswa_mapel_unique (nisn, mapel)
);

CREATE TABLE IF NOT EXISTS absensi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nisn VARCHAR(20) NOT NULL,
  tanggal DATE NULL,
  bulan VARCHAR(30) NOT NULL,
  hadir INT NOT NULL DEFAULT 0,
  sakit INT NOT NULL DEFAULT 0,
  izin INT NOT NULL DEFAULT 0,
  alpa INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY absensi_siswa_tanggal_unique (nisn, tanggal)
);

CREATE TABLE IF NOT EXISTS prestasi (
  id VARCHAR(40) PRIMARY KEY,
  judul VARCHAR(180) NOT NULL,
  kategori VARCHAR(30) NOT NULL,
  deskripsi TEXT NOT NULL,
  gambar LONGTEXT NULL,
  tanggal VARCHAR(30) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pengumuman (
  id VARCHAR(30) PRIMARY KEY,
  judul VARCHAR(150) NOT NULL,
  kategori VARCHAR(50) NOT NULL,
  target VARCHAR(30) NOT NULL,
  tanggal VARCHAR(30) NOT NULL,
  penting TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'Dipublikasikan',
  isi TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS materi_tugas (
  id VARCHAR(40) PRIMARY KEY,
  judul VARCHAR(150) NOT NULL,
  tipe ENUM('materi', 'tugas') NOT NULL,
  mapel VARCHAR(100) NOT NULL,
  kelas VARCHAR(30) NOT NULL,
  guru_nip VARCHAR(30) NOT NULL,
  guru VARCHAR(100) NOT NULL,
  tanggal VARCHAR(30) NOT NULL,
  deskripsi TEXT NOT NULL,
  file_name VARCHAR(255) NULL,
  file_type VARCHAR(120) NULL,
  file_data LONGTEXT NULL,
  deadline DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pesan_kontak (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL,
  subjek VARCHAR(150) NOT NULL,
  telepon VARCHAR(30) NULL,
  pesan TEXT NOT NULL,
  tujuan_email VARCHAR(120) NOT NULL DEFAULT 'seccondgilang@gmail.com',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
  setting_key VARCHAR(80) PRIMARY KEY,
  setting_value JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
